cargo-features = ["strip"]

[package]
name = "zenith"
version = "0.12.0"
authors = ["Benjamin Vaisvil"]
edition = "2018"
description = "Similar to top or htop but with CPU, Network Usage, and Disk Usage charts."
readme = "README.md"
homepage = "https://github.com/bvaisvil/zenith"
repository = "https://github.com/bvaisvil/zenith"
license = "MIT"
keywords = ["system monitor", "tui", "process monitor", "sysinfo"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"

[features]
default = []
nvidia = ["nvml-wrapper"]

[dependencies]
tui = { version = "0.14.*", features = ["crossterm"], default-features = false }
crossterm = "0.19"
byte-unit = "4.0.9"
users = "0.11.0"
num-derive = "0.3.0"
num-traits = "0.2"
heim = {git = "https://github.com/heim-rs/heim", rev = "0cc1540", features = ["full"]}
futures = "0.3.7"
gumdrop = {version = "0.8", features = ["default_expr"]}
chrono = "0.4.*"
sysinfo = {git = "https://github.com/bvaisvil/sysinfo.git", branch="zenith_changes_15.1"}
dirs-next = "2.0.0"
serde = { version="1.0.117", features=["derive"] }
serde_derive = "1.0.117"
bincode = "1.3.1"
battery = "0.7.*"
signal-hook = "0.3.3"
log = { version = "0.4.*"}
env_logger = { version = "0.8.1", default-features = false }
libc = "0.2"
nvml-wrapper = { version = "0.7.0", optional = true }
